version: "3.9"
   
services:
  postgres_db:
    image: postgres
    restart: always
    command: -p 5434
    env_file:
      - src/.env
    ports:
      - "5434:5434"
    expose:
      - 5434
    volumes:
      - postgres_data:/var/lib/postgresql/data

  superlink:
    depends_on:
      - postgres_db
    build:
      context: .
    volumes:
      - static:/static
      - media:/media
    ports:
      - "8080:8080"
    env_file:
      - src/.env

  nginx:
    depends_on:
      - superlink
    build:
      context: ./nginx
    ports:
      - "8888:80"
    volumes:
      - static:/static
      - media:/media

  grafana:
    image: grafana/grafana
    ports:
      - "35874:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always

  prometheus:
    depends_on:
      - superlink
    build:
      context: ./prometheus
    volumes:
      - prometheus-data:/prometheus
    ports:
      - 35875:9090

volumes:
  postgres_data:
  static:
  media:
