version: "3.9"
   
services:
  postgres_db:
    image: postgres
    restart: always
    command: -p 5434
    env_file:
      - src/.env
    ports:
      - "5434:5434"
    expose:
      - 5434
    volumes:
      - postgres_data:/var/lib/postgresql/data

  super_link:
    depends_on:
      - postgres_db
    build:
      context: .
    volumes:
      - static:/static
      - media:/media
    ports:
      - "8000:8000"
    env_file:
      - src/.env

  nginx:
    depends_on:
      - super_link
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - static:/static
      - media:/media

volumes:
  postgres_data:
  static:
  media: