global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["127.0.0.1:9090"]

  - job_name: "superlink"
    static_configs:
      - targets: ["superlink:8080"]
        labels:
          alias: "superlink"
