# Generated by Django 3.2.14 on 2022-07-14 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('profile_picture', models.ImageField(upload_to='accounts/supplier/profile_pictures/', verbose_name='Profile Picture')),
                ('birthdate', models.DateField(verbose_name='Birthdate')),
                ('identification_card', models.ImageField(upload_to='accounts/supplier/id/', verbose_name='Id Card')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('profile_picture', models.ImageField(upload_to='accounts/employee/profile_pictures/', verbose_name='Profile Picture')),
                ('birthdate', models.DateField(verbose_name='Birthdate')),
                ('identification_card', models.ImageField(upload_to='accounts/employee/id/', verbose_name='Id Card')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('profile_picture', models.ImageField(upload_to='accounts/delivery/profile_pictures/', verbose_name='Profile Picture')),
                ('birthdate', models.DateField(verbose_name='Birthdate')),
                ('identification_card', models.ImageField(upload_to='accounts/delivery/id/', verbose_name='Id Card')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
