# Generated by Django 3.2.14 on 2022-07-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='closed_time',
            field=models.DateTimeField(blank=True, verbose_name='Closed Time'),
        ),
    ]
