# Generated by Django 3.2.14 on 2022-07-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_cart_closed_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='closed_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Closed Time'),
        ),
    ]
