# Generated by Django 3.2.14 on 2022-07-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_cart_closed_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Discount'),
        ),
    ]
