# Generated by Django 3.2.14 on 2022-07-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_cartitem_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='payed',
            field=models.BooleanField(default=False, verbose_name='Payed'),
        ),
    ]
