# Generated by Django 3.2.14 on 2022-07-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_cart_payed'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='delivery',
            field=models.BooleanField(default=False, verbose_name='Delivery'),
        ),
    ]
