# Generated by Django 3.2.14 on 2022-07-14 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100)),
                ('productType', models.CharField(max_length=100)),
                ('Description', models.TextField(max_length=100)),
                ('Amount', models.CharField(max_length=100)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.producer')),
            ],
        ),
    ]
